import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
[font]
#normal = { family = "Comic Shanns Mono Nerd Font", style = "Regular" }
normal = { family = "Comic Shanns Mono ", style = "Regular" }
bold = { family = "Comic Shanns Mono ", style = "Bold" }
#normal = { family = "Comic Mono", style = "Regular" }
#bold = { family = "Comic Mono", style = "Bold" }
size = 13
